---
- name: Deploy To Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/2023maven-webappwith-ansible/target/2023maven-webappwith-ansible.war"
        dest: "/opt/tomcat/webapps/2023maven-webappwith-ansible.war"
        remote_src: no

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        /opt/tomcat/bin/startup.sh
